apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Release.Name }}:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM registry.redhat.io/ubi8/openjdk-21:1.21-2.1752676423

      ENV LANGUAGE="sv_SE:sv"

      COPY --chown=185 target/*.jar /deployments/

      EXPOSE 8080
      EXPOSE 8989
      USER 185

      ENV JAVA_APP_JAR="/deployments/*.jar"

      ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
    type: Dockerfile
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
